# Generated by Django 4.1 on 2022-09-22 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(choices=[('Patient', 'Patient'), ('Hospital_admin', 'Hospital_admin')], max_length=50)),
                ('phone_no', models.CharField(max_length=11)),
                ('status', models.CharField(choices=[('Registerd', 'Registered'), ('Unregisterd', 'Unregisterd')], max_length=100)),
                ('hospital_name', models.CharField(default='select', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
