# Generated by Django 4.1 on 2022-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='hospital_name',
            field=models.CharField(max_length=100),
        ),
    ]
