# Generated by Django 4.1 on 2022-09-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='Phone_no',
            field=models.TextField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='catagory',
            field=models.CharField(choices=[(1, 'Doctor'), (2, 'patient')], max_length=50),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], max_length=30),
        ),
    ]
