# Generated by Django 4.1 on 2022-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='hospital',
            field=models.CharField(default='unregister', max_length=100),
        ),
    ]
