# Generated by Django 4.1 on 2022-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_additionaluserinfo_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='hospital_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
