# Generated by Django 4.1 on 2022-09-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_additionaluserinfo_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluserinfo',
            old_name='hospital',
            new_name='status',
        ),
    ]
