# Generated by Django 4.1 on 2022-09-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_additionaluserinfo_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='Phone_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=30),
        ),
    ]
