# Generated by Django 4.1 on 2022-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_additionaluserinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='status',
            field=models.CharField(choices=[('Registerd', 'Registerd'), ('Unregisterd', 'Unregisterd')], default='Unregisterd', max_length=100),
        ),
    ]
