# Generated by Django 4.1 on 2022-09-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='name',
            new_name='hos_name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(db_column='hos_name', on_delete=django.db.models.deletion.CASCADE, to='main.hospital'),
        ),
    ]
