# Generated by Django 4.1 on 2022-09-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_hospital_hos_name_alter_doctor_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital',
            new_name='hos_name',
        ),
    ]
