# Generated by Django 4.1 on 2022-09-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_hospital_doctor_hos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
